# AWS SAM Template for AI Weekly Report Generator
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI Weekly Report Generator - Serverless Application

Parameters:
  AnthropicApiKey:
    Type: String
    NoEcho: true
    Description: Anthropic API Key for Claude
  
  GitHubToken:
    Type: String
    NoEcho: true
    Description: GitHub Personal Access Token (optional but recommended)
    Default: ""
  
  SenderEmail:
    Type: String
    Description: SES verified sender email address
    Default: ""
  
  RecipientEmail:
    Type: String
    Description: Email address to receive weekly reports
    Default: ""
  
  S3BucketName:
    Type: String
    Description: S3 bucket name for storing reports
    Default: ai-weekly-report-bucket

Resources:
  # S3 Bucket for storing reports
  ReportBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldReports
            Status: Enabled
            ExpirationInDays: 365
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub '${ReportBucket.Arn}/*'
        - PolicyName: SESAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource: '*'
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref ApiKeySecret

  # Secrets Manager for API keys
  ApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ai-weekly-report/api-keys
      Description: API keys for AI Weekly Report Generator
      SecretString: !Sub |
        {
          "ANTHROPIC_API_KEY": "${AnthropicApiKey}",
          "GITHUB_TOKEN": "${GitHubToken}"
        }

  # Lambda Function
  WeeklyReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-weekly-report-generator
      PackageType: Image
      ImageUri: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/ai-weekly-report:latest'
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 900  # 15 minutes
      MemorySize: 1024
      Environment:
        Variables:
          AWS_S3_BUCKET: !Ref S3BucketName
          SENDER_EMAIL: !Ref SenderEmail
          RECIPIENT_EMAIL: !Ref RecipientEmail
          SECRET_ARN: !Ref ApiKeySecret
          SEND_EMAIL: 'true'
      Events:
        WeeklySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 14 ? * FRI *)  # Every Friday at 2 PM UTC
            Description: Weekly AI report generation trigger
            Enabled: true

  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${WeeklyReportFunction}'
      RetentionInDays: 30

Outputs:
  FunctionName:
    Description: Lambda Function Name
    Value: !Ref WeeklyReportFunction
  
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt WeeklyReportFunction.Arn
  
  S3BucketName:
    Description: S3 Bucket for Reports
    Value: !Ref ReportBucket
  
  S3BucketArn:
    Description: S3 Bucket ARN
    Value: !GetAtt ReportBucket.Arn
  
  SecretArn:
    Description: Secrets Manager Secret ARN
    Value: !Ref ApiKeySecret

